version: "2"
services:
  app:
    container_name: journeys_app
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/opt/app
      - /opt/app/node_modules/
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://docker:a0b5c113x85@postgres:5432/postgres
    ports:
      - 3000
      - 3000:3000
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: a0b5c113x85
